### ISSUE TITLE
Request/bug ledger-enquirer.com

### ISSUE THREAD

**Issue by jmbphd** [bpc-clone/bpc_firefox_support#238]
Always first see changelog and search (domain) name in (all) issues (& use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request: "free article limit"

Link of paywalled article: https://www.ledger-enquirer.com/news/local/article294079169.html

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site): reader view does work, but it won't load as normal in browser – this is a new issue, it used to work

Browser (main version): Firefox 131.0.3 (aarch64)

BPC-extension version (number): 3.8.8.0

**Comment by bpc-clone** [comment]
McClatchy-group fixed in latest master/update rules (or next release).

**Comment by jmbphd** [comment]
Still getting a "You’ve reached your free article limit" box with 3.8.9 on Firefox – for example at this link:

https://www.ledger-enquirer.com/news/politics-government/article294465504.html

I'm opted into everything in the extension and have tried adding the domain as a custom site, but it already appears in the default list (double domain). Not sure if I'm missing something?

**Comment by bpc-clone** [comment]
Site is part of McClatchy Group, but only works when you opt-in to custom sites (do not add a custom site).\
Until next release also `Check for update rules at startup` in options (new fix wasn't working for custom flex sites).

**Comment by jmbphd** [comment]
All three things on the options page are enabled. I toggled them off and back on, and it asked for permissions to access all websites when I re-enabled custom sites. Now when I load the page, the article limit box no longer shows, but the text of the article still fades out in grey and the article is still cut off.

**Comment by bpc-clone** [comment]
Read closely: options (not opt-in).

**Comment by jmbphd** [comment]
> only works when you opt-in to custom sites (do not add a custom site).

"custom sites opt-in" is enabled, is that wrong?

Fwiw, all of the following on the options page are selected.

* BPC settings
x Show options on update
x Enable new sites by default
x Check for update rules at startup

**Comment by bpc-clone** [comment]
Domain was not recognized as a mcc-site (only in Firefox), but will be fixed in next release.
