### ISSUE TITLE
bug newsandtribune.com

### ISSUE THREAD

**Issue by ChrisW6969** [bpc-clone/bpc_firefox_support#388]
Always first see changelog and search (domain) name in (all) issues (&amp; use latest ext. version).
Also request host permission for unlisted domain (by clearing cookies once by BPC-icon/pin to extension toolbar): X = no fix).

Describe issue/request:

When I used the extension in Firefox, it worked perfectly until recently.

Now, when I go to http://newsandtribune.com, it still seems to be blocking the paywall successfully. However, when trying to read one of the articles on the site, the main paragraph of the article is gibberish. Like this:

kAmw@FD6 q:== ce[ E92E 3J E96 H2J :?4C65:3=J H2D G@E65 7@C 3J J@FC

Link of paywalled article:

https://www.newsandtribune.com/news/floyd-commissioners-to-pay-50-000-to-resolve-galena-digital-library-issue/article_82fdb03e-f95f-11ef-bc0a-1fe64345d030.html

Actions you tried yourself (mandatory) and if it works (clear cookies, disable javascript, change user-agent/referer, reader view, archive sites and/or add a custom site):

I completely removed Firefox and reinstalled it fresh. I completely removed bpc and reinstalled it, too. Oddly, you can read some of the webpage, except the main paragraph of the news story on that webpage.

Browser (main version): 135.0.1 (64-bit)
BPC-extension version (number): 4.0.5.3

**Comment by bpc-clone** [comment]
CNHI Group (opt-in to custom sites) fixed in latest master/update rules (or next release).

**Comment by ChrisW6969** [comment]
I have Version 4.0.7.0 Last Updated March 19, 2025. However, the error is still happening. See:

[https://www.newsandtribune.com/news/clark_county/services-directory/article_26b43b7a-d288-11ef-b4a7-4fb84ab8a9b7.html](url)





 Services Directory

    Jan 14, 2025

    1 min to read

Upcoming funeral services listed alphabetically from death notices published in the News and Tribune.
CLARK COUNTY
kAmzCF6C[ qC6?52 |2C:=J? — uF?6C2= |2DD `` 2]>] %9FCD52J[ 2E $E] y@9? !2F= xx[ (6DE $E] y@6 #5] r92A6=[ $6==6CD3FC8k^Am
kAm%9C@4<>@CE@?[ r92C=6D #@36CE — uF?6C2= |2DD `_ 2]>] $2EFC52J[ $E] p?E9@?J @7 !25F2 r2E9@=:4 r9FC49[ r=2C<DG:==6k^Am
k9bmu{~*s r~&}%*k^9bm
kAmz@496CE[ $E6A96? !9:=:A — uF?6C2= |2DD `` 2]>] uC:52J[ 2E ~FC {25J @7 !6CA6EF2= w6=A r2E9@=:4 r9FC49[ }6H p=32?Jk^Am
k9bm!xzt r~&}%*k^9bm
kAmu@DE6C[ %96@5@C6 #] — a A]>] $2EFC52J[ 2E ~]s] w2CC:D uF?6C2= w@>6[ !6E6CD3FC8k^Am
k9bm}t)% ~u zx}k^9bm
kAmr=2C< r@F?EJ r@C@?6C q:==J $4@EE :D D66<:?8 E96 ?6IE @7 <:? 7@C %:?2 |2E96D] p?J@?6 H:E9 :?7@C>2E:@? @? E96 56462D65[ A=62D6 4@?E24E E96 4@C@?6C’D @77:46 2E g`a\agd\eaga]k^Am

**Comment by bpc-clone** [comment]
Site works fine for me, but opt-in to custom sites & reload add-on or browser (site will be recognized as part of CNHI Group).\
PS no need to file new (same) issue.

**Comment by ChrisW6969** [comment]
Thank you. I turned off the extension and made sure to have the latest updates, and most recent version of Firefox also. I had previously entered the site in Custom Sites, so I took it out of that area, since you said it was already handled as part of CNHI Group. Now it is working again.
